name: 'Tests: node.js < 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '< 10'
      notable: '7.5 || 7.6' # 7.6.0 introduced AsyncFunction
      type: minors
      command: npm run tests-only
      skip-ls-check: true
